Repository MSK68/mlops_one, pull requests merged in 2024-05, with the labels that each got.

#1 Add diamonds-dataset.csv
  .dvc/.gitignore
  .dvc/config
  .dvcignore
Labels: enhancement

#9 App dev
  .gitignore
  Dockerfile
  app.py
  docker-compose.yaml
  html/static/.gitkeep
  html/static/brilliance.png
  html/templates/.gitkeep
  html/templates/home.html
  model/.gitkeep
  requirements.txt
Labels: enhancement

#11 Добавли Jenkinsfile
  Jenkinsfile
Labels: enhancement, High priority

#14 Add tests in test_app.py for app.py
  app.py
  test_app.py
Labels: enhancement, High priority

#15 Добавил обновление pip
  Dockerfile
Labels: bug

#16 Update README
  README.md
Labels: documentation
